#!/bin/sh
# osu! video and background killer
version='3'

# colours
red='\033[0;31m'
green='\033[0;32m'
blue='\033[0;34m'
purple='\033[0;35m'
clear='\033[0m'

# obgk config file 
config=$XDG_CONFIG_HOME/obgk/config

# thing that deletes stuff 
bgk() {
  echo -e "${green}finding $1${clear}" && find $dir -iname "*.$1" -type f -exec /bin/rm -vf {} \;
}

if [ -s $config ] # check if config file exists, if so use it as $dir
then
    dir=`cat $config`
    break  
else # no config file :(
  clear
  echo -e "obgk ${version} setup"
  echo -e "${red}this will delete every image and video if you dont put the right directory!!!!!!!!!!${clear}"

# check if zenity is available, if not fall back to old prompt
  if ! command -v zenity &> /dev/null; then # zenity is not available :(((
    echo -e "${purple}zenity was not found, please type in your osu song folder${clear}"
    read dir
    mkdir $XDG_CONFIG_HOME/obgk >> /dev/null 
    echo "$dir" > "$config"  
    clear

  else # zenity is available
    echo -e "${blue}zenity found, please select your osu songs folder${clear}"
    sleep 1 
    dir=`zenity --directory  --file-selection --title="select your osu songs folder"`
  
    case $? in
         0) mkdir $XDG_CONFIG_HOME/obgk 
            echo "$dir selected"
            echo "$dir" > "$config"
            sleep 0.75
            clear;;
         1)
            echo "no folder selected :("
            exit;;
        -1)
            clear
            echo -e "${red}something happened idk${clear}"
            exit;;
    esac
  fi
  
fi

if [[ -z $(grep '[^[:space:]]' $config) ]];  then # if the config file exists, but for whatever reason has nothing in it, then delete that config file and restart
  rm -r $config
  echo -e "${red}error:${clear} config file has no directory, please run obgk again"
  exit
fi

if test $(find $dir -name "*.osu" | head -n 3 | wc -l) -eq 0 # a failsafe, where if you dont put the right directory, it wont let you continued
then
  echo -e "${red}are you sure you put the right folder?${clear}"
  echo -e "${red}deleting config file${clear}"
  sleep 0.25
  /bin/rm -r $config
  exit
fi

echo -e "${blue}obgk${clear} version ${version}" 
echo -e "your music folder is in ${purple}$dir${clear}" 
echo -e "your config file is in ${green}$config${clear}"

# start
  bgk jpg
  bgk png
  bgk jpeg
  bgk bmp
  bgk mpg
  bgk flv
  bgk avi
  bgk mp4
  bgk jfif

